### ISSUE TITLE
Tons of errors in Home Assistant ZHA with UZG-01 v0.3

### ISSUE THREAD

**Issue by kylepyke** [mercenaruss/zigstar_gateways#38]
I'm getting so many errors and dropouts I don't know where to begin.

Here are some of the errors:

```
 Logger: zigpy.zcl
Source: runner.py:188
First occurred: 3:59:04 AM (4 occurrences)
Last logged: 3:59:04 AM

    [0xFF93:1:0x0019] Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/clusters/general.py", line 2191, in _handle_cluster_request await self._handle_image_block(*args, tsn=tsn, model=self.endpoint.model) File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/clusters/general.py", line 2312, in _handle_image_block await self.image_block_response( File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 411, in reply return await self._endpoint.reply( ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/endpoint.py", line 278, in reply return await self.device.reply( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 469, in reply return await self.request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 297, in request await self._application.request( File "/usr/local/lib/python3.11/site-packages/zigpy/application.py", line 768, in request await self.send_packet( File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 1061, in send_packet await self._send_request_raw( File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 952, in _send_request_raw response = await asyncio.shield( ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1067, in request_callback_rsp await self.request(request, timeout=timeout, **response_params) File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1021, in request self._uart.send(frame) ^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'send'
    [0x21BF:1:0x0019] Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/clusters/general.py", line 2191, in _handle_cluster_request await self._handle_image_block(*args, tsn=tsn, model=self.endpoint.model) File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/clusters/general.py", line 2312, in _handle_image_block await self.image_block_response( File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 411, in reply return await self._endpoint.reply( ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/endpoint.py", line 278, in reply return await self.device.reply( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 469, in reply return await self.request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 297, in request await self._application.request( File "/usr/local/lib/python3.11/site-packages/zigpy/application.py", line 768, in request await self.send_packet( File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 1061, in send_packet await self._send_request_raw( File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 952, in _send_request_raw response = await asyncio.shield( ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1067, in request_callback_rsp await self.request(request, timeout=timeout, **response_params) File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1021, in request self._uart.send(frame) ^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'send'
```

Another:

```


Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:145
First occurred: 3:56:12 AM (22 occurrences)
Last logged: 3:59:03 AM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1028, in request
    response = await response_future
               ^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1067, in request_callback_rsp
    await self.request(request, timeout=timeout, **response_params)
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1024, in request
    async with async_timeout.timeout(
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

```

Another:

```


Logger: zigpy_znp.zigbee.application
Source: /usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py:691
First occurred: 3:59:04 AM (1 occurrences)
Last logged: 3:59:04 AM
Watchdog check failed

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1028, in request
    response = await response_future
               ^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 689, in _watchdog_loop
    await self._znp.request(c.SYS.Ping.Req())
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1024, in request
    async with async_timeout.timeout(
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

```

Another:

```


Logger: zigpy_znp.zigbee.application
Source: /usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py:778
First occurred: 3:59:19 AM (1 occurrences)
Last logged: 3:59:19 AM
Failed to reconnect

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1028, in request
    response = await response_future
               ^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 772, in _reconnect
    await self.connect()
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 115, in connect
    await znp.connect()
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 726, in connect
    self.capabilities = (await self._skip_bootloader()).Capabilities
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 706, in _skip_bootloader
    return await self.request(c.SYS.Ping.Req())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 1024, in request
    async with async_timeout.timeout(
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError
```

Another:

```
Logger: zigpy.application
Source: runner.py:188
First occurred: 2:48:29 AM (13 occurrences)
Last logged: 2:49:04 AM

    Received relays from an unknown device: 0xFF93
    Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xFF93)
    Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x9D70)
    Received relays from an unknown device: 0xA995
    Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xA995)
```

I've been trying to work this out for days, and cannot get this coordinator to function properly. It constantly disconnects and needs to be restarted. There seems to be MAJOR issues that need to be addressed.

Some people have had similar issues– seemingly with the CC2652P/P7 chip:

https://github.com/home-assistant/core/issues/94381

https://community.home-assistant.io/t/tubeszb-cc2652p2-keeps-disconnecting-from-ha-since-zigbee2mqtt-last-update/538064/1

This link demonstrates a fix for the Sonoff-P dongle, but I'm not sure how it would be implemented with a ZigStar device:
https://community.home-assistant.io/t/zigbee2mqtt-not-starting-up-anymore/336312?u=lexcao

Please Advise.

**Comment by mercenaruss** [comment]
@kylepyke follow this thread and flash last firmware from Koenkk: https://github.com/Koenkk/Z-Stack-firmware/discussions/496
